// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWf2MfZD9zUqtDz3ilAoRmSBwhBqsYmoA',
    appId: '1:898566210557:web:f5328c2e52974081d88f94',
    messagingSenderId: '898566210557',
    projectId: 'testproject-ae59a',
    authDomain: 'testproject-ae59a.firebaseapp.com',
    storageBucket: 'testproject-ae59a.appspot.com',
    measurementId: 'G-VYCDZLH6QG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0VJ3bFBnatwH41igYfzwg_TfxpO5bqCk',
    appId: '1:898566210557:android:3ce14a261c5036d2d88f94',
    messagingSenderId: '898566210557',
    projectId: 'testproject-ae59a',
    storageBucket: 'testproject-ae59a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnWUv_mIfHqrWofci9HH8v-DNI2ZFqJLo',
    appId: '1:898566210557:ios:d24b47b82a164b0ad88f94',
    messagingSenderId: '898566210557',
    projectId: 'testproject-ae59a',
    storageBucket: 'testproject-ae59a.appspot.com',
    iosClientId: '898566210557-phva7tmkpeo522a3p7hcqrgl1qsl8udu.apps.googleusercontent.com',
    iosBundleId: 'com.example.mvvmproject.mvvmproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnWUv_mIfHqrWofci9HH8v-DNI2ZFqJLo',
    appId: '1:898566210557:ios:a600d1a3a9e752dad88f94',
    messagingSenderId: '898566210557',
    projectId: 'testproject-ae59a',
    storageBucket: 'testproject-ae59a.appspot.com',
    iosClientId: '898566210557-f71ii13bua3n1ukrgtihuisadn5hqp6e.apps.googleusercontent.com',
    iosBundleId: 'com.example.mvvmproject.mvvmproject.RunnerTests',
  );
}
